config/routes.rb
Rails.application.routes.draw do

  resources :apps
  resources :events

  devise_for :users

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  match 'events' => "events#options", via: :options

  root :to => 'apps#index'

end

app/models/app.rb
class App < ActiveRecord::Base

  validates :name, presence: true
  has_many :events
  belongs_to :user

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :app

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :apps

  def role?(base_role)
    role == base_role.to_s
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController

	def index
	  @apps = App.all
	end

	def new
	  @app = App.new
	  authorize @app
	end

	def show
	  @app = App.find(params[:id])
	  authorize @app
	end

	def create
	  @app = App.new(app_params)
          authorize @app
	  @app.user = current_user
          if @app.save
            redirect_to app_path(@app), notice: "App was added successfully." and return
          else
            flash[:error] = "Error adding app. Please try again."
            render :new and return
	  end #wyas elooking at something else
	end

	def edit
	  @app = App.find(params[:id])
          authorize @app
	  # edit action is responsible for rendering the view
	  # update action is responsible for interacting with the model
	end

	def update
	  @app = App.find(params[:id])
          authorize @app
          if @app.update_attributes(app_params)
            redirect_to @app and return
          else
            flash[:error] = "Error updating app. Please try again."
	    render :edit and return
	  end
	end

	def destroy
	  @app = App.find(params[:id])
          authorize @app
	  if @app.destroy
            flash[:notice] = "The app #{@app.name} was successfully deleted."
            redirect_to apps_path and return
          else
            flash[:error] = "There was an error deleting the app."
          end
  	end

	private

	def app_params
	  params.require(:app).permit(:name, :desc, :user_id)
	  # using strong_parameters here
	  # more: http://blog.sensible.io/2013/08/17/strong-parameters-by-example.html
	end
end

app/controllers/events_controller.rb
class EventsController < ActionController::Base
  respond_to :json
  before_filter :cors_set_headers
  after_filter :cors_set_access_control_headers
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def options
    render(:text => '', :content_type => 'text/plain')
  end

  def create
    @app = App.find(event_params[:app_id])
    @event = @app.events.build(event_params)
    if @event.save
      render json: @event
    else
      render json: @event.errors
    end
  end

  private

  def event_params
    params.require(:event).permit(:app_id, :ip_address, :web_property_id, :action, :updated_at, :created_at)
  end

  def cors_set_headers
    if request.method == :options
      common_cors_headers
      render(:text => '', :content_type => 'text/plain') and return
    end
  end

  def cors_set_access_control_headers
    common_cors_headers
  end

  def common_cors_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version, Content-Type'
    headers['Access-Control-Max-Age'] = "86400"
  end

  def not_found
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
	def pretty_up_time(app)
		app.created_at.to_time.strftime('%B %d, %Y')
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/apps/_form.html.slim
= form_for @app do |f|
  - if @app.errors.any?
    #error_explanation
      h2 = "#{pluralize(@app.errors.count, "error")} prohibited this app from being saved:"
      ul
        - @app.errors.full_messages.each do |message|
          li = message

  .field.col-md-3
    /= f.label :App_Name
    = f.text_field :name, class: 'form-control', :placeholder => "Name your app"
  .field.col-md-3
    /= f.label :App_description
    = f.text_field :desc, class: 'form-control', :placeholder => "Describe your app"
  .actions
    = f.submit 'Save', class: 'btn btn-success'

br

app/views/apps/edit.html.slim
h2 Change Your App Attributes

== render partial: 'form', object: @app

app/views/apps/index.html.slim
doctype html
html

- if current_user
  h1 Your Apps

  table class="app_categories"
    thead
      tr
        th width="25%"App name
        th width="40%"App description
        th width="20%"Date added
        th width="15%"Actions

    tbody
      - @apps.each do |app|
        - if current_user == app.user
          tr
            td #{link_to app.name, app}
            td #{app.desc}
            td #{pretty_up_time(app)}
            td #{link_to 'Edit', edit_app_path(app)} #{link_to 'Destroy', app, data: {:confirm => 'Are you sure?'}, :id => "destroy_#{app.id}", :method => :delete}

  br
    
    button.btn.btn-default.btn-sm #{link_to 'Create New App', new_app_path}

- else
  h1 Welcome to Blocmetrics! Please sign in.

app/views/apps/new.html.slim
h1 Add an App to Monitor

== render partial: 'form', object: @app

app/views/apps/show.html.slim
doctype html
html

.div #{@app.name}
.div #{@app.desc}
.div #{link_to 'Edit', edit_app_path(@app)}  #{link_to 'Destroy', @app, data: {:confirm => 'Are you sure?'}, :method => :delete}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title
      | Blocmetrics
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    meta name="description" content=""
    meta name="author" content=""
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-collapse"
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Blocmetrics", apps_path, :class => "navbar-brand"
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li.active.inline-nav
              - if current_user
                = link_to "Sign out", destroy_user_session_path, method: :delete
              - else
                = link_to "Sign in", new_user_session_path
              li
                = link_to "Sign up", new_user_registration_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do
          button.close type="button" data-dismiss="alert" aria-hidden="true"
            | &times;
          = msg
      = yield